default:
  tags:
    - docker

stages:
  - checkLintPython
  - pushHarbor
  - pushDockerHub
  - build

lint_black:
  stage: checkLintPython
  image: python:3.10
  before_script:
    - pip install black
  script:
    - black --check --diff .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - "*.py"
        - "**/*.py"

pushHarbor:
  stage: pushHarbor
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
    - apk add --update nodejs npm python3 make g++
    - npm install -g @devcontainers/cli
  script:
    - devcontainer build --config .devcontainer/x86/devcontainer.json --workspace-folder . --image-name simoverlord:latest
    - docker tag simoverlord $HARBOR_HOST/$HARBOR_PROJECT/my-app:$CI_JOB_ID
    - docker tag simoverlord $HARBOR_HOST/$HARBOR_PROJECT/my-app:latest
    - docker push harbor.pg.innopolis.university/sim_overlord100/my-app:latest
  rules:
    - if: ($CI_COMMIT_BRANCH == "yml_tests" || $CI_COMMIT_BRANCH == "master") && ($CI_PIPELINE_SOURCE == "push")

pushDockerHub:
  stage: pushDockerHub 
  image: docker:24.0.5 
  services: 
    - docker:24.0.5-dind 
  before_script: 
    - docker login -u simoverlord100 -p "$DOCKER_HUB_PASSWORD" 
    - apk add --update nodejs npm python3 make g++ 
    - npm install -g @devcontainers/cli 
  script: 
    - devcontainer build --config .devcontainer/x86/devcontainer.json --workspace-folder . --image-name simoverlord:latest 
 
    - docker push simoverlord:latest 
  rules: 
    - if: ($CI_COMMIT_BRANCH == "yml_tests" || $CI_COMMIT_BRANCH == "master") && ($CI_PIPELINE_SOURCE == "push")


build_image:
  stage: build
  image: docker:27.0.0-rc.1-cli
  services:
    - docker:27.0.0-rc.1-dind
  before_script:
    - apk add --no-cache --upgrade sudo
  script:
    - cd .devcontainer
    - mkdir /container
    - sudo chown -R $(whoami) /container
    - sudo docker build -t my-app:latest .
    - sudo docker run --rm --mount  type=bind,source=$(pwd),target=/home/mobile/ws my-app:latest /bin/bash -c "source /opt/ros/humble/setup.bash"
    - apk update
    - apk upgrade
    - apk add --no-cache python3 py3-pip build-base python3-dev bash
    - python3 -m venv /venv
    - . /venv/bin/activate
    - pip install -U colcon-common-extensions
    - colcon build
  rules:
    - if: ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master") && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "pull_request")

