name: cpp linting
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install linter
        run: |
          python -m pip install --upgrade pip
          pip install cpplint
          cpplint --recursive --quiet .
      - name: run linter
        run: |
          cpplint --recursive --quiet .
